config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

 
    get 'perdeu', to: 'items#lost', as: 'perdeu'

    get 'achou', to: 'items#found', as: 'achou'

    post 'cadastrar_item' => 'items#create', as: :cadastrar_item

end

app/models/item.rb
class Item < ActiveRecord::Base
	extend TimeSplitter::Accessors
  split_accessor :date
	has_one :person
	accepts_nested_attributes_for :person
  validates :title,:description,:local, :date, presence:true 
  mount_uploader :image, ImageUploader



end

app/models/person.rb
class Person < ActiveRecord::Base
	belongs_to :item
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, :email,  presence:true
	validates :email, format:{ with:VALID_EMAIL_REGEX}
	
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   add_flash_types :error
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
  end

  def create
   @items =Item.all
   @item = Item.new(item_params, status:0)

   if @item.save
     redirect_to :action => 'lost'
   else 
     redirect_to :back, error:@item.errors.full_messages
   end

   

  end


  def add_item
  end

  def remove_item
  end

  def lost
    @item = Item.new
    @item.build_person
    @items = Item.all
   
  end

  def found
  end
  

  def item_params
      params.require(:item).permit(:title, :local, :description, :date, person_attributes:[:email, :name, :phone])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/home/index.html.erb
 <div class="parallax-container valign-wrapper">
    <div class="parallax"><%=image_tag 'olar1.jpg' %></div>

 



<div class="row valign">
 
        <div class=" superior ">
            <span class=" amatic-sc center-align fs-title shadow-green   "> <b>A C H A D O S</b></span>
            <h4 class=" amatic-sc center-align fs-title  ">&</h4>
            <span class=" amatic-sc center-align fs-title  shadow-green "> <b>P E R D I D O S </b></span>
            <div class="center align">
             <a href="#chico"><i id = 'arrow' class=" hvr-float shadow-black large material-icons valign  ">keyboard_arrow_down</i></a></div>

            
        </div>
        
    </div>


 </div>
 <div class="divider"></div>
 <div class="botton">
<div class="row pad">
    <div id="chico" class="  scrollspy col  s12 l6 m12   ">
        <div class="hideme center-align ">
            <%= link_to root_path, class:'waves-effect waves-light ' do %>
            <%=image_tag 'happy.png', class: 'center-align responsive-img  '%>
            <%end%>
        </div>
        <div class="hideme center-align">
            <%= link_to root_path, class:'waves-effect waves-light btn-flat btn-large' do %>
            <h4> <span class="indie-flower"> <b>Achei !</b></span></h4>
            <%end%>
        </div>
       
    </div>
    <div class="  col s12 l6 m12 ">
        <div class=" hideme center-align">
            <%= link_to perdeu_path , class:'waves-effect waves-light' do %>
            <%=image_tag 'sad.png', class: ' responsive-img center-align'%>
            <%end%>
        </div>
        <div class=" hideme center-align">
            <%= link_to perdeu_path , class:'waves-effect waves-light btn-flat btn-large' do %>
            <h4> <span class="indie-flower"> <b>Perdi !</b></span></h4>
            <%end%>
        </div>
    </div>
</div>
</div>

app/views/items/found.html.erb
<div class="row">
	<div class="col s12 m12 l6"></div>
	<div class="col s12 m12 l6"></div>
</div>

app/views/items/lost.html.erb
<div class="row">


	<div class="col s12 m12 l12">
     <h3 class=" amatic-sc center-align"><b> Perdeu?!</b></h3>
  
  
        
     


     
    <%= form_for(@item, url: cadastrar_item_path, html:{ class:"  col s12 m12 l12"}) do |f| %>

    


     <div class="row">

      
      <div class="input-field col l6 m6 s12">
        <i class="material-icons prefix">live_help</i>
        <%= f.text_field :title, class: "validate", required:"" %> 
        <%= f.label :title, "O QUÊ ?", class:"  indie-flower fss" %>
      </div> 

       <div class="input-field col l6 m6 s12">
        <i class="material-icons prefix">location_on</i>
        <%= f.text_field :local, class: "validate", id:" onde",required:"" %> 
        <%= f.label :local, "ONDE ?", class:"indie-flower fss" %>
       </div> 

    </div>

      <div class="row">


        <div class="input-field col l6 m6 s12">
         <i class="material-icons prefix">mode_edit</i>
        <%= f.text_area :description, class:"materialize-textarea", required:"" %>
        <%= f.label :description, "COMO É ?", class: "indie-flower fss"%>
        </div>


        
       <div class="input-field col l6 m6 s12">
         <i class="material-icons prefix">event</i>
      
        <%= f.text_field :date, id:"calendar2", class:"campoData",required:"" %>
        <%= f.label :date, "QUANDO ?", class: "indie-flower fss"%>
        </div>
       
      </div>


     <%= f.fields_for :person do |person_form| %>
     <div class="row">
        <div class="input-field col l6 m6 s12">
         <i class="material-icons prefix">account_circle</i>
        <%= person_form.text_field :name, class:"materialize-textarea", required:"" %>
        <%= person_form.label :name, "DE QUEM É ?", class: "indie-flower fss"%>
        </div>


        
       <div class="input-field col l6 m6 s12">
        <i class="material-icons prefix">mail_outline</i>      
        <%= person_form.email_field :email, class: "validate", required:"" %>
        <%= person_form.label :email, "EMAIL DO DONO", class: "indie-flower fss"%>
        </div>
     </div>
     <div class="row">
       <div class="input-field col l6 m6 s6">
         <i class="material-icons prefix">call</i>
         <%=person_form.text_field :phone, id: "campoPhone",class: "validate", required:""%>
         <%=person_form.label :phone, "TELEFONE PARA CONTATO", class:"indie-flower fss"%>
       </div>
   
     <%end%>


    
      <div class="col s6 l6 m6 center-align">
        <%= button_tag class:" hvr-float waves-effect waves-light btn-large black", method: :post do %>
          <span class="indie-flower white-text fss"> BOTA PARA ACHAR !</span>


        <%end%>
      </div>
      
        </div>


     <%end%> 

		
	</div>
  <div class="col s12 m12 l12">
     <h3 class=" amatic-sc center-align"><b> Já viu se tá por aqui ?</b></h3>
     <div  class="pad2">
       <table class="centered highlight responsive-table ">
        <thead>
          <tr>
              <th class = "indie-flower"data-field="what">O QUÊ</th>
              <th class = "indie-flower"data-field="how_is_it">COMO É</th>
              <th class = "indie-flower"data-field="where">ONDE</th>
              <th class = "indie-flower"data-field="when">QUANDO</th>
          </tr>
        </thead>

        <tbody>
        <% @items.each do |item|%>
          <tr>
            <td class="raleway"><%=item.title%></td>
            <td class="raleway"><%=item.description%></td>
            <td class="raleway"><%=item.local%></td>
            <td class="raleway"><%=item.date%></td>

          </tr>
          <%end%>
        </tbody>
      </table>
      </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
<div class="col s12 l6 m12">

	
</div>
<div class="col s12 l6 m12">
	
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LostAndFound</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
</head>
<body>
<%= error%>
<%= yield %>

 <footer class="page-footer transparent">
 <div class="divider"></div>
          <div class="container ">
            <div class="row">
              
            </div>
          </div>
          <div class="footer-copyright light-green lighten-1 ">
            <div class="container">
            <div class="left">
            <span class="grey-text text-lighten-4" href="#!">Desenvolvido por: </span>
              
                   <%=image_tag 'mandacaru2.png', class: ' responsive-image '%>
            <span class="amatic-sc fsm "> <b> M a n d a c a r u </b> <span class="black-text">T.I</span></span>
                    </div>

            
            
            </div>
           
          </div>
        </footer>
            
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @item.errors.any? %>
    <% @item.errors.full_messages.each do |msg| %>
      <%= msg %>
    <% end %>
<% end %>